# Generated by Django 5.2.5 on 2025-08-17 11:23

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImeiCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{15}$')])),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(help_text='15-digit IMEI number', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'IMEI must be 15 digits'), core.validators.validate_imei])),
                ('owner_name', models.CharField(help_text='Name of the phone owner', max_length=100)),
                ('phone_model', models.CharField(help_text='Brand and model', max_length=100)),
                ('last_seen_location', models.CharField(blank=True, max_length=255)),
                ('contact_info', models.CharField(help_text='Phone or email', max_length=150)),
                ('proof_of_ownership', models.FileField(blank=True, help_text='Receipt, photo, or proof of ownership', null=True, upload_to='reports/proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
